### ISSUE TITLE
Issue with image name in docker_sdk : "tf2_docker_sdk_api:latest" for docker compose in run_gpu.yml

### ISSUE THREAD

**Issue by AllenJoshey** [BMW-InnovationLab/BMW-TensorFlow-Training-GUI#58]
After completing a successful GPU build of the tool, While executing Docker compose an error occurs stating that  "tf2_docker_sdk_api:latest " does not exist or that permission to access is denied.
![image](https://user-images.githubusercontent.com/35285538/202799789-1d9088e7-3aa6-4cd2-9992-8e2433437bf6.png)
Below are the images created post the successful build(with build_gpu.yaml)..

![image](https://user-images.githubusercontent.com/35285538/202799673-21bf5f4e-9663-4400-994f-60fef7fea426.png)
Am I missing something here and if yes where does the tf2_docker_sdk_api exist?Or is this a naming issue conflicting with the run_gpu.yaml under docker_sdk?
where tf2_docker_sdk_api should be replaced with "tf2_training_api_gpu "(since mine is a gpu build)
It seems to be working when this is done

**Comment by AllenJoshey** [comment]
Attached is the expected result when the change to run_gpu.yml is made

![image](https://user-images.githubusercontent.com/35285538/202801915-a86d241e-d68c-49c2-bd89-fe4e1ed70b04.png)

**Comment by hadikoub** [comment]
Hello, 

Can you verify that the build_gpu and run_gpu content is the same as inside the GitHub repository?

build_gpu.yml: 

```version: '2.3'

services:

  docker_sdk:
    image: tf2_docker_sdk_api
    build:
      context: ./docker_sdk_api
      dockerfile: docker/Dockerfile
      args:
        http_proxy: 
        https_proxy:
  
  training_api:
    image: tf2_training_api_gpu
    build:
      context: ./training_api
      dockerfile: docker/GPU/Dockerfile
      args:
        http_proxy:
        https_proxy:
  
  user_interface:
    image: tf2_gui
    build:
      context: ./gui
      dockerfile: ./Dockerfile
      args:
        http_proxy:
        https_proxy:

  inference_api:
    image: tf2_inference_api_cpu
    build:
      context: ./inference_api
      dockerfile: docker/dockerfile
      args:
        http_proxy:
        https_proxy:
```

run_gpu.yml:

```
version: '2.3'

services:

  docker_sdk:
    image: tf2_docker_sdk_api:latest
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    network_mode: "host"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./datasets:/datasets
      - ./checkpoints:/checkpoints
      - ./docker_sdk_api:/docker_sdk_api
      - ./training_api:/training_api
      - ./tensorboards:/tensorboards

  user_inteface:
    image: tf2_gui:latest
    ports:
      - "4200:80"

  inference_api:
    image: tf2_inference_api_cpu:latest
    ports:
    - "4343:4343"
    volumes:
    - ./inference_api/models:/models
    - ./inference_api/models_hash:/models_hash

```

As you can see in the `build_gpu.yml` the `tf2_docker_sdk_api` is being built while in the `run_gpu.yml` the container is started.
